# @format

name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: LearningOS_2022
        uses: ./scripts
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTION_ACCESS }}
        with:
          source_file: ucore-rv-64-limingth.json
          destination_repo: 'os2edu/data'
          destination_folder: 'students'
          user_email: 'zyj17715640603@gmail.com'
          user_name: 'Jack-Zhang-1314'
          commit_message: 'A custom message for the commit'
